### ISSUE TITLE
javascript errors on testing 

### ISSUE THREAD

**Issue by ghost** [iogbole/gentelella_on_rails#5]
Hello, 

I use rspec with poltergeist to test some links 

But now I see this error : 

```
Failure/Error: visit "/"
     Capybara::Poltergeist::JavascriptError:
       One or more errors were raised in the Javascript code on the page. If you don't care about     these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

   TypeError: 'null' is not an object (evaluating 'this.canvas.getContext')
   TypeError: 'null' is not an object (evaluating 'this.canvas.getContext')
       at http://127.0.0.1:42147/assets/application-5ec24aef0b8573e4e9780d7e0260b79de277c06be8fbcd3df655a145f91c68af.js:14634 in b
       at http://127.0.0.1:42147/assets/application-5ec24aef0b8573e4e9780d7e0260b79de277c06be8fbcd3df655a145f91c68af.js:14651
 # /usr/local/rvm/gems/ruby-2.3.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/browser.rb:351:in `command'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/browser.rb:34:in `visit'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/poltergeist-1.9.0/lib/capybara/poltergeist/driver.rb:95:in `visit'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/session.rb:233:in `visit'
 # /usr/local/rvm/gems/ruby-2.3.0/gems/capybara-2.7.1/lib/capybara/dsl.rb:52:in `block (2 levels) in <module:DSL>'
 # ./spec/features/invoer_financiele_accounts_spec.rb:6:in `block (2 levels) in <top (required)>'

Finished in 2.18 seconds (files took 14.08 seconds to load)
1 example, 1 failure
```

**Comment by iogbole** [comment]
Please file any JS errors directlly with the Gentelella team. Thanks.
